### PR TITLE
Add more badges

### PR DESCRIPTION
**Pull request by Toinane**
#1 - I update readme.md with more badges :)

### CODE REVIEW

**Comment by Toinane** [comment]
it's already flat version for me :/ no ?

**Comment by itaditya** [comment]
Have you appended style=flat-square in each svg url ?

**Comment by Toinane** [comment]
Here you go :)
Just one things, the heroku badge doesn't have a square shape :/
screen

**Comment by itaditya** [comment]
Awesome !!!
and for heroku shield instead of square, it had to be flat.

**Comment by Toinane** [comment]
oh okey :D I see that, thank's!

**Pull request merged**
