### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by Toinane**
#13 - l've made some logo :) : 
- one in colors of the app
- the same in white version

### CODE REVIEW

**Comment by itaditya** [comment]
Wonderful logo, however I need something a little different. Can you please read this https://github.com/itaditya/Code-Runner/pull/10#issuecomment-337908395 .

In total try to add text in the logo also preferrably alongside it.

**Comment by itaditya** [comment]
Hey I didn't find anything new.. Have you took my points into consideration??
Also place the logo in client folder

**Comment by Toinane** [comment]
I work too, I can't work on open-source everyday.
I make another version, but I can't spend much time on design

**Comment by itaditya** [comment]
I thought, you had opened a new PR, but then I checked and there were no commits. That's why I asked. Totally my mistake, really sorry. 
Also keep up the good work

**Comment by Toinane** [comment]
no worries :) can you explain more what you want to change or what I keep?

**Comment by itaditya** [comment]
Attach a screenshot hinting the possible location for the logo, you probably would had something in mind while designing the logo

**Comment by Toinane** [comment]
I haven't no times to design actually :/ and my only way to design is at my work, so i will close this PR but you can use my previous work as you want!

**Pull request closed without merging**
